name: Build LaTeX document
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      PAPER: ${{ github.event.repository.name }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ env.PAPER }}.tex
          working_directory: .
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          pre_compile: git config --global --add safe.directory /github/workspace
        env:
          TEXINPUTS: ".:$PWD/../latex-styles-master/styles//:"
          BSTINPUTS: ".:$PWD/../latex-styles-master/styles/common"
          BIBINPUTS: ".:$PWD/../latex-styles-master/share"
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            ${{ env.PAPER }}.pdf
